name: ink blots
favicon: null
layout_spectrum: 0.6741797351278365
typography_spectrum: 0.7018356232438236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.14437140407972038
  lightness: 0.06525458791293204
  saturation: 0.43560713180340827
  rhythmicContrast: 0.7534561522770673
purpose: []
